// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhuyqrFh7305C5jbGBBICjD13K-5g2UJc',
    appId: '1:514231564507:web:fe8f88bab37c7a1f1a74fe',
    messagingSenderId: '514231564507',
    projectId: 'fb-caddy-project',
    authDomain: 'fb-caddy-project.firebaseapp.com',
    storageBucket: 'fb-caddy-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI1UcLxRkwaihHB8MotoeYJcs25WOtGGQ',
    appId: '1:514231564507:android:96bb358018ee7fbb1a74fe',
    messagingSenderId: '514231564507',
    projectId: 'fb-caddy-project',
    storageBucket: 'fb-caddy-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7rl9tbh34HdU3hkxFtJkVKV4QwIPbomg',
    appId: '1:514231564507:ios:6781f97c79edcc0f1a74fe',
    messagingSenderId: '514231564507',
    projectId: 'fb-caddy-project',
    storageBucket: 'fb-caddy-project.firebasestorage.app',
    iosBundleId: 'com.example.fbCaddyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7rl9tbh34HdU3hkxFtJkVKV4QwIPbomg',
    appId: '1:514231564507:ios:6781f97c79edcc0f1a74fe',
    messagingSenderId: '514231564507',
    projectId: 'fb-caddy-project',
    storageBucket: 'fb-caddy-project.firebasestorage.app',
    iosBundleId: 'com.example.fbCaddyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhuyqrFh7305C5jbGBBICjD13K-5g2UJc',
    appId: '1:514231564507:web:eed213fa76798dab1a74fe',
    messagingSenderId: '514231564507',
    projectId: 'fb-caddy-project',
    authDomain: 'fb-caddy-project.firebaseapp.com',
    storageBucket: 'fb-caddy-project.firebasestorage.app',
  );
}
